apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: jc0npp57f-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-87d7d8a936.46c4.p3.openshiftapps.com/rhtap/rhtap-qe-java-springboot:ccf2ec77207f26247e86ea9768df0fc8e113d0ff@sha256:6c797734eb080b7ed08f22d5a67c134ec82a3f017c5c2e43e4681c469408547a
          name: container-image
